# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EChoose' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EChoose
  source 'https://github.com/CocoaPods/Specs.git'

  pod 'Starscream', '~> 4.0.0'

  target 'EChooseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EChooseUITests' do
    # Pods for testing
  end

end
